{% set name = "wexpect" %}
{% set version = "3.3.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/wexpect-{{ version }}.tar.gz
  sha256: a734eb1ae8a3be6b29458c72deb352a742d32ce67fb291cdfd36652534d3f7e5

build:
  number: 0
  skip: true  # [unix]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pbr
    - pip
    - python
  run:
    - psutil
    - python
    - pywin32

test:
  imports:
    - wexpect
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/wexpect/
  dev_url: https://github.com/raczben/wexpect
  summary: Windows alternative of pexpect
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
